// <auto-generated />
using System;
using GoatVaultInfrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoatVaultInfrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227002841_AddArgon2ParametersToUser")]
    partial class AddArgon2ParametersToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("GoatVaultCore.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<byte[]>("AuthSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("AuthVerifier")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("MfaSecret")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("ShamirEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("VaultSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GoatVaultCore.Models.User", b =>
                {
                    b.OwnsOne("GoatVaultCore.Models.Objects.Argon2Parameters", "Argon2Parameters", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("HashLength")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Argon2HashLength");

                            b1.Property<int>("Lanes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Argon2Lanes");

                            b1.Property<int>("MemoryCost")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Argon2MemoryCost");

                            b1.Property<int>("Threads")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Argon2Threads");

                            b1.Property<int>("TimeCost")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Argon2TimeCost");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GoatVaultCore.Models.VaultEncrypted", "Vault", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<byte[]>("AuthTag")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("VaultAuthTag");

                            b1.Property<byte[]>("EncryptedBlob")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("VaultEncryptedBlob");

                            b1.Property<byte[]>("Nonce")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("VaultNonce");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Argon2Parameters")
                        .IsRequired();

                    b.Navigation("Vault")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
